enum CONTEXT_KEYS {
    PAGE = 'page',
    SLIDE = 'slide',
    SANITY_DATA = 'sanity_data',
    SCROLL_ENABLE = 'scroll_enable'
}

enum SECTION_NAMES {
    SERVICES = 'SERVICES',
    TWO_D_ANIMATION_SERVICE = 'TWO_D_ANIMATION_SERVICE',
    THREE_D_ANIMATION_SERVICE = 'THREE_D_ANIMATION_SERVICE',
    VIDEO_PRODUCTION_SERVICE = 'VIDEO_PRODUCTION_SERVICE',
    CASES = 'CASES',
    CLIENTS = 'CLIENTS',
    FEEDBACKS = 'FEEDBACKS',
    TEAM = 'TEAM',
    CONTACT_US = 'CONTACT_US'
}

enum SERVICE_TYPE {
    'VIDEO_PRODUCTION' = 'video-production',
    '2D_ANIMATION' = '2d-animation',
    '3D_ANIMATION' = '3d-animation'
}

enum SECTION_BACKGROUND {
    WHITE = 'white',
    BLACK = 'black'
}

enum SECTION_NUMBER {
    SHOWREEL,
    SERVICES,
    CASES,
    CLIENTS,
    FEEDBACKS,
    // TEAM,
    CONTACT_US
}

export {
    SECTION_NAMES,
    SECTION_NUMBER,
    CONTEXT_KEYS,
    SECTION_BACKGROUND,
    SERVICE_TYPE
}
