import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Showreel from '../src/sections/Showreel'
import Services from '../src/sections/Services'
import ScrollHandler from '../src/components/ScrollHandler';
import { Container } from 'react-bootstrap';
import { SECTION_BACKGROUND } from '../src/enum';
import { SECTION_TITLES } from '../src/constants/sectionTitles';
import Page from '../src/components/Page';
import Cases from '../src/sections/Cases';

const Home: NextPage = () => {

  return (
    <div>
      <Head>
        <title>Parsec Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container fluid className="px-0">
          <ScrollHandler>
            <Page id="showreel" fluid={false}>
              <Showreel />
            </Page>
            <Page id="services" sectionTitle={SECTION_TITLES.SERVICES} background={SECTION_BACKGROUND.BLACK}>
              <Services />
            </Page>
            <Page id="cases" sectionTitle={SECTION_TITLES.CASES} background={SECTION_BACKGROUND.WHITE}>
              <Cases />
            </Page>
          </ScrollHandler>
        </Container>
      </main>
    </div>
  )
}

export default Home
