import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../src/components/Header'
import Showreel from '../src/components/Showreel'

// export async function getServerSideProps() {

//   const allProjects = await SanityClient.fetch(
//     `*[_type == "project"]{
//     title,
//     slug,
//     video,
//   }`)

//   return {
//     props: {
//       allProjects
//     }, // will be passed to the page component as props
//   }
// }

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Parsec Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>     
      <main>                  
            <Header />
            <Showreel />          
      </main>
    </div>
  )
}

export default Home
