import type { NextPage } from 'next'
import Head from 'next/head'
import dynamic from 'next/dynamic'
// @ts-ignore
const PageSlider = dynamic(() => import('../src/components/PageSlider'), {
    ssr: false
})
// import { ISlideConfig, PageSlides, SlideParallaxType } from 'react-page-slides';

const Test: NextPage = () => {

    return (
        <div>
            <Head>
                <title>Parsec Studio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <style>
                    
                </style>
            </Head>
            <main>
                <PageSlider />
            </main>
        </div>
    )
}

export default Test