import type { NextPage } from 'next'
import Head from 'next/head'
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css';

const Test: NextPage = () => {

    return (
        <div>
            <Head>
                <title>Parsec Studio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Swiper
                    spaceBetween={50}
                    slidesPerView={1}
                    // direction="vertical"
                    // mousewheel={true}
                    onSlideChange={() => console.log('slide change')}
                    onSwiper={(swiper) => console.log(swiper)}
                >
                    <SwiperSlide>Slide 1</SwiperSlide>
                    <SwiperSlide>Slide 2</SwiperSlide>
                    <SwiperSlide>Slide 3</SwiperSlide>
                    <SwiperSlide>Slide 4</SwiperSlide>                    
                </Swiper>
            </main>
        </div>
    )
}

export default Test