import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState, useRef } from 'react'
import Showreel from '../src/sections/Showreel'
import Services from '../src/sections/Services'
import ScrollHandler from '../src/components/ScrollHandler';
import { Container } from 'react-bootstrap';
import { SECTION_BACKGROUND } from '../src/enum';
import { SECTION_TITLES } from '../src/constants/sectionTitles';
// import Page from '../src/components/Page';
import Cases from '../src/sections/Cases';
import { motion, motionValue, useTransform, useViewportScroll } from "framer-motion"
import { Page, Scroll } from 'framer'


// preventing context menu || devtools
// window.oncontextmenu = function () {
//   return false;
// };

// document.addEventListener("keydown", function(event){
//     var key = event.key || event.keyCode;

//     if (key == 123) {
//         return false;
//     } else if ((event.ctrlKey && event.shiftKey && key == 73) || (event.ctrlKey && event.shiftKey && key == 74)) {
//         return false;
//     }
// }, false);


// You can't copy any text.
// <br/>
// <textarea>You can't copy any text.</textarea>
// <script>
// document.body.addEventListener("copy", function(e){
//  e.preventDefault();
//  e.stopPropagation();
// });
// document.body.addEventListener("cut", function(e){
//  e.preventDefault();
//  e.stopPropagation();
// });
// </script>

const Test: NextPage = () => {

    const [currentPage, setCurrentPage] = useState(0)

    return (
        <div>
            <Head>
                <title>Parsec Studio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Page
                    height={'100%'}
                    width={"100%"}                    
                    alignment="start"
                    direction="vertical"
                    defaultEffect="coverflow"
                    momentum={false}
                    gap={0}
                    dragEnabled={false}
                    wheelEnabled={true}
                >
                    <motion.div style={{ color: 'white', width: '100vw', height: '100vh', backgroundColor: 'red' }}>A</motion.div>
                    <motion.div style={{ color: 'white', width: '100vw', height: '100vh', backgroundColor: 'blue' }}>B</motion.div>
                    <motion.div style={{ color: 'white', width: '100vw', height: '100vh', backgroundColor: 'green' }}>C</motion.div>
                    <motion.div style={{ color: 'white', width: '100vw', height: '100vh', backgroundColor: 'green' }}>C</motion.div>
                    <motion.div style={{ color: 'white', width: '100vw', height: '100vh', backgroundColor: 'green' }}>C</motion.div>
                    <motion.div style={{ color: 'white', width: '100vw', height: '100vh', backgroundColor: 'green' }}>C</motion.div>
                </Page>

                {/* <Container fluid className="px-0">

        </Container> */}
            </main>
        </div>
    )
}

export default Test
